### PR TITLE
fix #17 - add Docker support

### LINKED ISSUE #17: Create Dockerfile

### PR DESCRIPTION
**Pull request by paralax**
minimal Alpine image, uses docker-compose to easily expose port 9100

### CODE REVIEW

**Comment by sa7mon** [comment]
Thank you for the contribution! I'll review the code and merge into the `docker` branch in the next few days, then merge into master after testing.

**Comment by sa7mon** [comment]
@paralax Were you able to successfully connect to the docker container with PRET? I tried connecting with both PRET and netcat and the connection was refused both times.

**Comment by paralax** [comment]
I was yeah. How did you spin it up? I used `docker-compose` and it exposed the port for me ok. 

What does `docker ps` say?

**Comment by sa7mon** [comment]
I also used `docker-compose`. 

A `docker ps` returns the following:

```
$ docker ps
CONTAINER ID        IMAGE               COMMAND                 CREATED              STATUS              PORTS                    NAMES
681a682090b7        miniprint           "python3 ./server.py"   About a minute ago   Up 2 seconds        0.0.0.0:9100->9100/tcp   miniprint_miniprint_1
```

The `0.0.0.0` ip is to be expected since I use Docker Toolbox due to my older hardware. The above output looks like it's supposed to so I'm not sure what the issue would be

**Pull request merged**
